import type { Metadata } from 'next';
import { IBM_Plex_Sans_JP } from 'next/font/google';
import './globals.css';

const ibmPlexSansJP = IBM_Plex_Sans_JP({
  weight: ['400', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${ibmPlexSansJP.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
